using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraScript : MonoBehaviour {

    public float accelerationSpeed = 10.0f;
    public float rotationSpeed = 20.0f;
    public GameObject rotatingAround;

    private Rigidbody rigid;

	// Use this for initialization
	void Start () {
        rigid = GetComponent<Rigidbody>();
	}
	
	// Update is called once per frame
	void FixedUpdate () {
        rigid.angularVelocity = Vector3.zero;
        if (Input.GetKey(KeyCode.UpArrow) || Input.GetKey(KeyCode.W)) {
            rigid.AddForce(transform.forward * accelerationSpeed);
        }
        if (Input.GetKey(KeyCode.DownArrow) || Input.GetKey(KeyCode.S)) {
            rigid.AddForce(-transform.forward * accelerationSpeed / 2);
        }
        if (Input.GetKey(KeyCode.LeftArrow) || Input.GetKey(KeyCode.A)) {
            //rigid.AddForce(-transform.right * accelerationSpeed / 2);
            transform.Rotate(0, -rotationSpeed * Time.deltaTime, 0);
        }
        if (Input.GetKey(KeyCode.RightArrow) || Input.GetKey(KeyCode.D)) {
            //            rigid.AddForce(transform.right * accelerationSpeed / 2);
            transform.Rotate(0, rotationSpeed * Time.deltaTime, 0);
        }
        if (Input.GetKey(KeyCode.Space)) {
            rigid.AddForce(0, accelerationSpeed/2, 0);
        }
        if (Input.GetKey(KeyCode.LeftControl) || Input.GetKey(KeyCode.RightControl)) {
            rigid.AddForce(0, -accelerationSpeed / 2, 0);
        }

    }
}
